"""
Autonomous Background Ingestion Pipeline & AI Router.

Features:
- Project-wide directory scanner targeting dataset files (.json, .csv, .db, .parquet, .tsv).
- Resumable manifest tracking (file-level and record-level) in darknight.db.
- Atomic database transactions preventing duplicates or data loss on process restart.
- Hybrid Classifier Engine:
  - Uses Anthropic API when ANTHROPIC_API_KEY is present.
  - Falls back to offline heuristic classifier when API key is absent, tagging metadata with {"classified_by": "heuristic"}.
- Auto-creation of dynamic EntityTypes and ActivityTypes recorded in backend/data/canonical_schema_extensions.py.
- Prominent logging of identifier collisions to identifier_collisions.log.
- CLI interface and FastAPI background task integration.
"""

from __future__ import annotations
import sys
import os
import glob
import hashlib
import json
import logging
import asyncio
import argparse
from datetime import datetime, timezone
from typing import List, Dict, Any, Tuple, Optional

# Ensure backend root is on sys.path
BACKEND_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if BACKEND_DIR not in sys.path:
    sys.path.insert(0, BACKEND_DIR)

from database import engine, SessionLocal, init_db
from data.canonical_schema import (
    EntityModel, TransactionModel, ObservationModel,
    IngestionFileManifestModel, IngestionRecordManifestModel, EntityType
)
import data.canonical_schema_extensions as extensions

# Logging setup
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("ingest_ai_router")

NEW_CATEGORIES_LOG = os.path.join(BACKEND_DIR, "new_categories_created.log")
IDENTIFIER_COLLISIONS_LOG = os.path.join(BACKEND_DIR, "identifier_collisions.log")
EXTENSIONS_FILE_PATH = os.path.join(BACKEND_DIR, "data", "canonical_schema_extensions.py")

# Directories to exclude from project-wide scanning
EXCLUDE_DIRS = {
    "node_modules", ".venv", "venv", ".git", "__pycache__", "dist", "build",
    "artifacts", "scratch", ".idea", ".vscode", "brain", ".gemini"
}

# Global status tracker for GET /api/ingestion-status endpoint
INGESTION_STATUS: Dict[str, Any] = {
    "status": "idle",  # idle, scanning, processing, completed, error
    "files_total": 0,
    "files_processed": 0,
    "records_total": 0,
    "records_processed": 0,
    "new_categories_created": [],
    "last_run": None,
    "error": None
}


def compute_file_hash(filepath: str) -> str:
    """Computes SHA-256 hash of a file."""
    hasher = hashlib.sha256()
    try:
        with open(filepath, "rb") as f:
            while chunk := f.read(8192):
                hasher.update(chunk)
        return hasher.hexdigest()
    except Exception as e:
        logger.error(f"Error computing hash for {filepath}: {e}")
        return ""


def log_new_category(category_name: str, category_type: str, source_file: str):
    """Logs auto-created category to dedicated file, memory status, and canonical_schema_extensions.py."""
    msg = f"[AUTO-CATEGORY CREATED] Type: {category_type} | Category: '{category_name}' | Source: {source_file}"
    logger.warning(msg)

    # Append to log file
    with open(NEW_CATEGORIES_LOG, "a", encoding="utf-8") as f:
        f.write(f"{datetime.now(timezone.utc).isoformat()} - {msg}\n")

    # Update memory status
    INGESTION_STATUS["new_categories_created"].append({
        "category_name": category_name, "category_type": category_type, "source_file": source_file, "timestamp": datetime.now(timezone.utc).isoformat()
    })

    # Update extensions python file
    try:
        if category_type == "EntityType" and category_name not in extensions.DYNAMIC_ENTITY_TYPES:
            extensions.DYNAMIC_ENTITY_TYPES[category_name] = f"Auto-created EntityType from {source_file}"
        elif category_type == "ActivityType" and category_name not in extensions.DYNAMIC_ACTIVITY_TYPES:
            extensions.DYNAMIC_ACTIVITY_TYPES[category_name] = f"Auto-created ActivityType from {source_file}"

        # Write back python registry
        with open(EXTENSIONS_FILE_PATH, "w", encoding="utf-8") as f:
            f.write(f'"""\nCanonical Schema Extensions Registry.\nAuto-generated by backend/pipelines/ingest_ai_router.py\n"""\n\n')
            f.write(f'DYNAMIC_ENTITY_TYPES = {json.dumps(extensions.DYNAMIC_ENTITY_TYPES, indent=4)}\n\n')
            f.write(f'DYNAMIC_ACTIVITY_TYPES = {json.dumps(extensions.DYNAMIC_ACTIVITY_TYPES, indent=4)}\n\n')
            f.write(f'AUTO_CREATED_CATEGORIES_LOG = {json.dumps(INGESTION_STATUS["new_categories_created"], indent=4)}\n')
    except Exception as e:
        logger.error(f"Failed writing extensions file: {e}")


def log_identifier_collision(identifier: str, existing_id: str, source_file: str):
    """Logs identifier collision to dedicated log file."""
    msg = f"[IDENTIFIER COLLISION] Identifier '{identifier}' already registered as '{existing_id}'. Merged source telemetry from {source_file}."
    logger.warning(msg)
    with open(IDENTIFIER_COLLISIONS_LOG, "a", encoding="utf-8") as f:
        f.write(f"{datetime.now(timezone.utc).isoformat()} - {msg}\n")


class HybridClassifier:
    """Hybrid Classifier using Anthropic API when key is available, heuristic fallback otherwise."""

    def __init__(self):
        self.api_key = os.environ.get("ANTHROPIC_API_KEY")
        self.use_ai = bool(self.api_key)
        if self.use_ai:
            logger.info("HybridClassifier: Anthropic API Key detected. Using LLM classification.")
        else:
            logger.info("HybridClassifier: ANTHROPIC_API_KEY absent. Using Heuristic Classifier fallback.")

    def classify_batch(self, batch_records: List[Dict[str, Any]], source_file: str) -> List[Tuple[str, Dict[str, Any]]]:
        """
        Classifies a batch of records.
        Returns list of tuples: (bucket_type, mapped_data)
        where bucket_type is 'entity', 'transaction', or 'observation'.
        """
        if self.use_ai:
            try:
                return self._classify_with_anthropic(batch_records, source_file)
            except Exception as e:
                logger.error(f"Anthropic API call failed ({e}). Falling back to heuristic classifier.")

        return self._classify_with_heuristic(batch_records, source_file)

    def _classify_with_heuristic(self, batch_records: List[Dict[str, Any]], source_file: str) -> List[Tuple[str, Dict[str, Any]]]:
        results = []
        for idx, record in enumerate(batch_records):
            keys_lower = {str(k).lower(): v for k, v in record.items()}

            # 1. Transaction Check (Connections)
            if any(k in keys_lower for k in ["from_address", "source_entity", "tx_hash", "sender_wallet"]):
                src = str(keys_lower.get("from_address") or keys_lower.get("source_entity") or keys_lower.get("sender_wallet") or "unknown_source")
                tgt = str(keys_lower.get("to_address") or keys_lower.get("target_entity") or keys_lower.get("receiver_wallet") or "unknown_target")
                amt_raw = keys_lower.get("amount") or 0.0
                try:
                    amt_float = float(str(amt_raw).split()[0])
                except (ValueError, IndexError):
                    amt_float = 0.0

                mapped = {
                    "id": str(keys_lower.get("id") or keys_lower.get("tx_hash") or f"tx_{hashlib.md5(json.dumps(record, default=str).encode()).hexdigest()[:12]}"),
                    "tx_hash": str(keys_lower.get("tx_hash")) if keys_lower.get("tx_hash") else None,
                    "source_entity_id": src,
                    "target_entity_id": tgt,
                    "amount": amt_float,
                    "amount_str": str(amt_raw),
                    "currency": str(keys_lower.get("currency") or "BTC"),
                    "timestamp": keys_lower.get("timestamp") or datetime.now(timezone.utc).isoformat(),
                    "metadata": {k: v for k, v in record.items() if k not in ["id", "tx_hash", "from_address", "to_address", "source_entity", "target_entity", "amount", "currency", "timestamp"]}
                }
                mapped["metadata"]["classified_by"] = "heuristic"
                results.append(("transaction", mapped))

            # 2. Event Check (Observations)
            elif any(k in keys_lower for k in ["message_text", "activity_type", "latitude", "src_ip", "channel_id"]):
                entity_id = str(keys_lower.get("entity_id") or keys_lower.get("channel_id") or keys_lower.get("sender_handle") or keys_lower.get("src_ip") or f"entity_anon_{idx}")
                act_type = str(keys_lower.get("activity_type") or ("telegram_message" if "message_text" in keys_lower else "network_flow" if "src_ip" in keys_lower else "general_observation"))

                if act_type not in extensions.DYNAMIC_ACTIVITY_TYPES:
                    log_new_category(act_type, "ActivityType", source_file)

                mapped = {
                    "id": str(keys_lower.get("id") or f"obs_{hashlib.md5(json.dumps(record, default=str).encode()).hexdigest()[:12]}"),
                    "entity_id": entity_id,
                    "source": str(keys_lower.get("source") or keys_lower.get("platform") or "FileIngest"),
                    "timestamp": keys_lower.get("timestamp") or datetime.now(timezone.utc).isoformat(),
                    "latitude": float(keys_lower["latitude"]) if "latitude" in keys_lower and keys_lower["latitude"] is not None else None,
                    "longitude": float(keys_lower["longitude"]) if "longitude" in keys_lower and keys_lower["longitude"] is not None else None,
                    "region": str(keys_lower["region"]) if "region" in keys_lower and keys_lower["region"] is not None else None,
                    "activity_type": act_type,
                    "risk_signal": str(keys_lower.get("risk_signal")) if keys_lower.get("risk_signal") else None,
                    "metadata": {k: v for k, v in record.items() if k not in ["id", "entity_id", "source", "timestamp", "latitude", "longitude", "region", "activity_type", "risk_signal"]}
                }
                mapped["metadata"]["classified_by"] = "heuristic"
                results.append(("observation", mapped))

            # 3. Entity Check (Things)
            else:
                identifier = str(keys_lower.get("identifier") or keys_lower.get("address") or keys_lower.get("url") or keys_lower.get("primary_alias") or keys_lower.get("name") or f"id_{idx}")
                ent_type = str(keys_lower.get("type") or keys_lower.get("entity_type") or ("wallet" if "address" in keys_lower else "listing" if "price" in keys_lower else "suspect"))

                if ent_type not in [e.value for e in EntityType] and ent_type not in extensions.DYNAMIC_ENTITY_TYPES:
                    log_new_category(ent_type, "EntityType", source_file)

                mapped = {
                    "id": str(keys_lower.get("id") or f"ent_{hashlib.md5(identifier.encode()).hexdigest()[:12]}"),
                    "type": ent_type,
                    "identifier": identifier,
                    "display_name": str(keys_lower.get("display_name") or keys_lower.get("title") or keys_lower.get("primary_alias") or identifier),
                    "platform": str(keys_lower.get("platform") or "FileIngest"),
                    "location": str(keys_lower.get("location")) if keys_lower.get("location") else None,
                    "risk_score": int(keys_lower.get("risk_score") or 0),
                    "metadata": {k: v for k, v in record.items() if k not in ["id", "type", "identifier", "display_name", "title", "platform", "location", "risk_score"]}
                }
                mapped["metadata"]["classified_by"] = "heuristic"
                results.append(("entity", mapped))

        return results

    def _classify_with_anthropic(self, batch_records: List[Dict[str, Any]], source_file: str) -> List[Tuple[str, Dict[str, Any]]]:
        import httpx
        headers = {
            "x-api-key": self.api_key,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json"
        }
        prompt = f"""
You are an expert law-enforcement data classification AI.
Classify each record into one of three canonical buckets: 'entity', 'transaction', or 'observation'.
Return JSON array of items: {{"bucket": "entity|transaction|observation", "mapped_data": {{...}}}}
Input records: {json.dumps(batch_records)}
"""
        response = httpx.post(
            "https://api.anthropic.com/v1/messages",
            headers=headers,
            json={
                "model": "claude-3-5-sonnet-20241022",
                "max_tokens": 4096,
                "messages": [{"role": "user", "content": prompt}]
            },
            timeout=30.0
        )

        if response.status_code == 200:
            res_data = response.json()
            content = res_data["content"][0]["text"]
            parsed = json.loads(content)
            results = []
            for item in parsed:
                mapped = item["mapped_data"]
                mapped["metadata"] = mapped.get("metadata", {})
                mapped["metadata"]["classified_by"] = "anthropic_ai"
                results.append((item["bucket"], mapped))
            return results
        else:
            raise RuntimeError(f"Anthropic API error {response.status_code}: {response.text}")


class DirectoryScanner:
    """Scans workspace for dataset files while honoring exclusion lists."""

    def __init__(self, root_dir: str):
        self.root_dir = root_dir

    def scan(self) -> List[str]:
        target_files = []
        for root, dirs, files in os.walk(self.root_dir):
            # Prune excluded directories in-place
            dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS and not d.startswith(".")]

            for file in files:
                if file.endswith((".json", ".csv", ".db", ".parquet", ".tsv")) and not file.startswith("."):
                    full_path = os.path.normpath(os.path.join(root, file))
                    # Ignore manifest/internal db files
                    if "darknight.db" in full_path or "mock_db.json" in full_path:
                        continue
                    target_files.append(full_path)
        return target_files


class IngestionEngine:
    """Manages idempotent background ingestion, manifest tracking, and atomic persistence."""

    def __init__(self):
        self.classifier = HybridClassifier()

    def process_file(self, file_path: str):
        logger.info(f"Processing ingestion target file: {file_path}")
        file_hash = compute_file_hash(file_path)
        if not file_hash:
            return

        db = SessionLocal()
        try:
            manifest = db.query(IngestionFileManifestModel).filter(IngestionFileManifestModel.file_path == file_path).first()
            if manifest and manifest.status == "completed" and manifest.content_hash == file_hash:
                logger.info(f"File '{file_path}' already processed and hash matches. Skipping.")
                db.close()
                return

            if not manifest:
                manifest = IngestionFileManifestModel(
                    file_path=file_path, content_hash=file_hash, status="in_progress"
                )
                db.add(manifest)
                db.commit()
            else:
                manifest.content_hash = file_hash
                manifest.status = "in_progress"
                db.commit()

            # Parse file records
            records = self._read_file_records(file_path)
            manifest.total_records = len(records)
            db.commit()

            # Batch processing with atomic record manifest updates
            batch_size = 20
            for i in range(0, len(records), batch_size):
                batch = records[i:i + batch_size]
                self._process_record_batch(db, file_path, batch, i)
                manifest.processed_records = min(len(records), i + len(batch))
                db.commit()

            manifest.status = "completed"
            manifest.updated_at = datetime.now(timezone.utc)
            db.commit()
            logger.info(f"Successfully completed ingestion of file '{file_path}' ({len(records)} records).")

        except Exception as e:
            db.rollback()
            logger.error(f"Failed processing file '{file_path}': {e}", exc_info=True)
            if manifest:
                manifest.status = "failed"
                db.commit()
        finally:
            db.close()

    def _read_file_records(self, file_path: str) -> List[Dict[str, Any]]:
        records = []
        if file_path.endswith(".json"):
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    if isinstance(data, list):
                        records = data
                    elif isinstance(data, dict):
                        for k, v in data.items():
                            if isinstance(v, list):
                                records.extend(v)
            except Exception as e:
                logger.error(f"Error reading JSON file {file_path}: {e}")
        elif file_path.endswith((".csv", ".tsv")):
            import csv
            delim = "\t" if file_path.endswith(".tsv") else ","
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    reader = csv.DictReader(f, delimiter=delim)
                    records = list(reader)
            except Exception as e:
                logger.error(f"Error reading CSV file {file_path}: {e}")
        return records

    def _process_record_batch(self, db, file_path: str, batch: List[Dict[str, Any]], start_index: int):
        records_to_classify = []
        record_keys = []

        for idx, rec in enumerate(batch):
            rec_key = f"{file_path}:{start_index + idx}"
            rec_hash = hashlib.md5(json.dumps(rec, default=str).encode()).hexdigest()

            # Check per-record manifest status for resumability
            rec_manifest = db.query(IngestionRecordManifestModel).filter(IngestionRecordManifestModel.id == rec_key).first()
            if rec_manifest and rec_manifest.status in ["mapped", "new_category_created"]:
                continue  # Skip already completed record (resumability check)

            records_to_classify.append((rec_key, rec_hash, rec))

        if not records_to_classify:
            return

        batch_raw = [r[2] for r in records_to_classify]
        classified_results = self.classifier.classify_batch(batch_raw, file_path)

        # Atomic commit: canonical record + manifest status
        for (rec_key, rec_hash, rec), (bucket, mapped) in zip(records_to_classify, classified_results):
            rec_manifest = db.query(IngestionRecordManifestModel).filter(IngestionRecordManifestModel.id == rec_key).first()
            if not rec_manifest:
                rec_manifest = IngestionRecordManifestModel(
                    id=rec_key, file_path=file_path, record_hash=rec_hash, status="pending"
                )
                db.add(rec_manifest)

            canonical_id = mapped.get("id") or f"res_{rec_hash[:12]}"
            rec_manifest.canonical_record_id = canonical_id

            if bucket == "entity":
                identifier = mapped.get("identifier") or canonical_id
                existing_ent = db.query(EntityModel).filter(EntityModel.identifier == identifier).first()
                if existing_ent:
                    # Identifier collision handling
                    existing_ent.risk_score = max(existing_ent.risk_score, mapped.get("risk_score", 0))
                    existing_ent.metadata_json.setdefault("collisions", []).append({
                        "file": file_path, "mapped": mapped
                    })
                    log_identifier_collision(identifier, existing_ent.id, file_path)
                else:
                    e_model = EntityModel(
                        id=canonical_id,
                        type=mapped.get("type", "suspect"),
                        identifier=identifier,
                        display_name=mapped.get("display_name"),
                        platform=mapped.get("platform"),
                        location=mapped.get("location"),
                        risk_score=mapped.get("risk_score", 0),
                        metadata_json=mapped.get("metadata", {})
                    )
                    db.add(e_model)

            elif bucket == "transaction":
                t_model = TransactionModel(
                    id=canonical_id,
                    tx_hash=mapped.get("tx_hash"),
                    source_entity_id=mapped.get("source_entity_id", "unknown"),
                    target_entity_id=mapped.get("target_entity_id", "unknown"),
                    amount=mapped.get("amount", 0.0),
                    amount_str=mapped.get("amount_str", "UNSPECIFIED"),
                    currency=mapped.get("currency", "BTC"),
                    metadata_json=mapped.get("metadata", {})
                )
                db.add(t_model)

            elif bucket == "observation":
                o_model = ObservationModel(
                    id=canonical_id,
                    entity_id=mapped.get("entity_id", "unknown"),
                    source=mapped.get("source", "FileIngest"),
                    latitude=mapped.get("latitude"),
                    longitude=mapped.get("longitude"),
                    region=mapped.get("region"),
                    activity_type=mapped.get("activity_type", "general_observation"),
                    risk_signal=mapped.get("risk_signal"),
                    metadata_json=mapped.get("metadata", {})
                )
                db.add(o_model)

            rec_manifest.status = "mapped"
            rec_manifest.updated_at = datetime.now(timezone.utc)

        db.commit()  # Atomic transaction commit


def run_full_pipeline_scan():
    """Runs full background pipeline scan."""
    global INGESTION_STATUS
    init_db()
    INGESTION_STATUS["status"] = "scanning"
    INGESTION_STATUS["last_run"] = datetime.now(timezone.utc).isoformat()

    logger.info("Starting Full Project Data Scan & Ingestion Pipeline...")
    scanner = DirectoryScanner(root_dir=BACKEND_DIR)
    target_files = scanner.scan()

    INGESTION_STATUS["files_total"] = len(target_files)
    INGESTION_STATUS["status"] = "processing"
    logger.info(f"Discovered {len(target_files)} candidate dataset files across project.")

    engine_instance = IngestionEngine()
    for file_path in target_files:
        engine_instance.process_file(file_path)
        INGESTION_STATUS["files_processed"] += 1

    INGESTION_STATUS["status"] = "completed"
    logger.info("Background Data Ingestion Pipeline Scan Completed!")


async def start_background_ingestion_task():
    """FastAPI Non-blocking background task runner."""
    loop = asyncio.get_event_loop()
    await loop.run_in_executor(None, run_full_pipeline_scan)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Canonical Data Ingestion AI Router CLI")
    parser.add_argument("--full-scan", action="store_true", help="Scan entire project directory for dataset files")
    parser.add_argument("--file", type=str, help="Ingest specific dataset file")
    args = parser.parse_args()

    init_db()
    engine_instance = IngestionEngine()

    if args.file:
        if os.path.exists(args.file):
            engine_instance.process_file(args.file)
        else:
            logger.error(f"File not found: {args.file}")
    else:
        run_full_pipeline_scan()
