import React, { useState, useEffect } from "react";
import {
  listInvestigationReports,
  getInvestigationReport,
  generateInvestigationReport,
} from "../../../api/investigationReportsApi";
import { Button } from "../../ui/button";
import { useAuth } from "../../../context/AuthContext";
import {
  AlertCircle,
  CheckCircle,
  RefreshCw,
  ScrollText,
  ArrowLeft,
  Plus,
  Eye,
  ShieldCheck,
  Cpu,
  Hash,
  Calendar,
  User,
} from "lucide-react";

/* ── helpers ── */
const STATUS_COLORS = {
  GENERATED: "text-emerald-400 bg-emerald-950/60 border-emerald-700",
  DRAFT: "text-yellow-400 bg-yellow-950/60 border-yellow-700",
};

function MetaField({ label, value, mono = false }) {
  return (
    <div>
      <dt className="text-muted-foreground text-[10px] uppercase">{label}</dt>
      <dd className={`text-xs${mono ? " font-mono text-primary" : ""}`}>{value || "—"}</dd>
    </div>
  );
}

/* ── Evidence references table ── */
function EvidenceReferenceTable({ evidenceReferences }) {
  const entries = Object.entries(evidenceReferences || {});
  if (entries.length === 0) return null;
  return (
    <div className="pt-3 border-t border-border/40 space-y-2">
      <h5 className="text-[10px] text-muted-foreground uppercase font-bold tracking-wider">
        Evidence Traceability Map ({entries.length} items)
      </h5>
      <div className="space-y-1.5">
        {entries.map(([refKey, meta]) => (
          <div
            key={refKey}
            className="p-2.5 bg-background border border-border/50 rounded text-[11px] space-y-0.5"
          >
            <div className="flex items-center gap-2">
              <span className="font-bold text-primary font-mono">{refKey}</span>
              <span className="text-muted-foreground">·</span>
              <span className="text-foreground font-medium">{meta.source_name || "Unknown Source"}</span>
              {meta.source_type && (
                <span className="text-muted-foreground text-[10px]">({meta.source_type})</span>
              )}
            </div>
            {meta.source_url && (
              <p className="text-blue-400 truncate">{meta.source_url}</p>
            )}
            {meta.integrity_hash && (
              <p className="text-muted-foreground font-mono truncate">
                SHA-256: {meta.integrity_hash}
              </p>
            )}
            {meta.collected_at && (
              <p className="text-muted-foreground">
                Collected: {new Date(meta.collected_at).toLocaleString("en-IN")}
              </p>
            )}
            {meta.review_notes && (
              <p className="text-muted-foreground italic">Note: {meta.review_notes}</p>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}

/* ── Report Detail View ── */
function ReportDetail({ report, onBack }) {
  return (
    <div className="space-y-4 font-mono">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-border/40 pb-2">
        <div className="flex items-center gap-2">
          <ScrollText className="w-4 h-4 text-primary" />
          <h3 className="font-bold text-sm text-primary uppercase">Report Detail</h3>
          <span className="text-xs text-muted-foreground">[{report.report_id}]</span>
        </div>
        <Button
          size="sm"
          variant="ghost"
          onClick={onBack}
          className="h-7 gap-1 text-xs"
        >
          <ArrowLeft className="w-3 h-3" /> Back
        </Button>
      </div>

      {/* Metadata */}
      <div className="p-4 bg-card/40 border border-border/50 rounded space-y-3">
        <dl className="grid grid-cols-2 gap-x-6 gap-y-1.5 text-xs">
          <MetaField label="Report ID" value={report.report_id} mono />
          <MetaField
            label="Status"
            value={
              <span className={`px-1.5 py-0.5 rounded border text-[10px] font-bold uppercase ${STATUS_COLORS[report.status] || "text-muted-foreground"}`}>
                {report.status}
              </span>
            }
          />
          <MetaField label="Model Used" value={report.model_used} mono />
          <MetaField label="Generated By" value={report.created_by_email} />
          <div className="col-span-2">
            <MetaField
              label="Generated At"
              value={report.created_at ? new Date(report.created_at).toLocaleString("en-IN") : "—"}
            />
          </div>
        </dl>
      </div>

      {/* Report Content */}
      <div className="space-y-2">
        <h4 className="text-[10px] text-muted-foreground uppercase font-bold tracking-wider">
          Intelligence Report Content
        </h4>
        <div className="p-4 bg-background border border-border/60 rounded text-[11px] leading-relaxed whitespace-pre-wrap max-h-[500px] overflow-y-auto font-mono">
          {report.content || "No report content available."}
        </div>
      </div>

      {/* AI Disclaimer */}
      {report.structured_data?.ai_disclaimer && (
        <div className="p-3 bg-yellow-950/20 border border-yellow-700/40 text-yellow-400 text-[10px] rounded flex items-start gap-2">
          <AlertCircle className="w-3.5 h-3.5 flex-shrink-0 mt-0.5" />
          {report.structured_data.ai_disclaimer}
        </div>
      )}

      {/* Evidence References */}
      <EvidenceReferenceTable evidenceReferences={report.evidence_references} />
    </div>
  );
}

/* ── Main ReportsTab ── */
export default function ReportsTab({ investigationId, canManage }) {
  const { triggerReAuth } = useAuth();
  const [reports, setReports] = useState([]);
  const [total, setTotal] = useState(0);
  const [selectedReport, setSelectedReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [showGenerateForm, setShowGenerateForm] = useState(false);
  const [customTitle, setCustomTitle] = useState("");

  useEffect(() => {
    loadReports();
  }, [investigationId]);

  const loadReports = async () => {
    setLoading(true);
    setError("");
    try {
      const data = await listInvestigationReports(investigationId);
      setReports(data.reports || []);
      setTotal(data.total || 0);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const showSuccessMsg = (msg) => {
    setSuccess(msg);
    setTimeout(() => setSuccess(""), 4000);
  };

  const handleGenerate = () => {
    triggerReAuth(async () => {
      setGenerating(true);
      setError("");
      try {
        const result = await generateInvestigationReport(
          investigationId,
          customTitle.trim() || null,
        );
        showSuccessMsg(`Report "${result.title}" generated successfully.`);
        setCustomTitle("");
        setShowGenerateForm(false);
        loadReports();
      } catch (err) {
        setError(err.message);
      } finally {
        setGenerating(false);
      }
    });
  };

  const handleSelectReport = async (report) => {
    setError("");
    try {
      const detail = await getInvestigationReport(investigationId, report.report_id);
      setSelectedReport(detail);
    } catch (err) {
      setError(err.message);
    }
  };

  /* ── Detail view ── */
  if (selectedReport) {
    return (
      <ReportDetail
        report={selectedReport}
        onBack={() => setSelectedReport(null)}
      />
    );
  }

  /* ── List view ── */
  return (
    <div className="space-y-4 font-mono">
      {/* Header */}
      <div className="flex items-center justify-between gap-3 flex-wrap">
        <div className="flex items-center gap-2 text-xs text-muted-foreground">
          <ScrollText className="w-3.5 h-3.5 text-primary" />
          <span className="font-bold text-foreground">{total}</span> intelligence reports
        </div>
        <div className="flex gap-2">
          <Button
            size="sm"
            variant="ghost"
            onClick={loadReports}
            disabled={loading}
            className="h-7 gap-1 text-xs"
          >
            <RefreshCw className={`w-3 h-3 ${loading ? "animate-spin" : ""}`} />
          </Button>
          {canManage && (
            <Button
              size="sm"
              onClick={() => {
                setShowGenerateForm(!showGenerateForm);
                setError("");
              }}
              className="h-7 gap-1 text-xs"
            >
              <Plus className="w-3 h-3" /> Generate Report
            </Button>
          )}
        </div>
      </div>

      {/* Generate form */}
      {showGenerateForm && canManage && (
        <div className="p-4 bg-card/60 border border-border/60 rounded space-y-2 text-xs">
          <p className="text-muted-foreground text-[10px] uppercase font-bold">
            New Intelligence Report
          </p>
          <input
            type="text"
            placeholder="Custom report title (optional — AI will generate one if blank)"
            value={customTitle}
            onChange={(e) => setCustomTitle(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && handleGenerate()}
            className="w-full bg-background border border-border/60 rounded px-2 py-1.5 text-xs"
          />
          <p className="text-muted-foreground text-[10px]">
            Requires re-authentication. The report will be grounded exclusively on reviewed findings and promoted evidence.
          </p>
          <div className="flex gap-2 justify-end">
            <Button
              size="sm"
              variant="ghost"
              onClick={() => { setShowGenerateForm(false); setCustomTitle(""); }}
              className="text-xs h-7"
            >
              Cancel
            </Button>
            <Button
              size="sm"
              onClick={handleGenerate}
              disabled={generating}
              className="text-xs h-7 gap-1"
            >
              <Cpu className="w-3 h-3" />
              {generating ? "Generating..." : "Generate"}
            </Button>
          </div>
        </div>
      )}

      {/* Feedback banners */}
      {error && (
        <div className="p-3 bg-destructive/10 border border-destructive/40 text-destructive text-xs rounded flex items-center gap-2">
          <AlertCircle className="w-4 h-4 flex-shrink-0" /> {error}
        </div>
      )}
      {success && (
        <div className="p-3 bg-emerald-500/10 border border-emerald-500/40 text-emerald-400 text-xs rounded flex items-center gap-2">
          <CheckCircle className="w-4 h-4 flex-shrink-0" /> {success}
        </div>
      )}

      {/* Report list */}
      {loading ? (
        <p className="text-xs text-muted-foreground animate-pulse">Loading reports...</p>
      ) : reports.length === 0 ? (
        <div className="p-6 text-center text-xs text-muted-foreground border border-dashed border-border/40 rounded bg-card/30">
          <ScrollText className="w-8 h-8 text-muted-foreground/40 mx-auto mb-2" />
          No intelligence reports generated yet. Mark findings as RELEVANT in the Intelligence tab,
          promote them to evidence in the Findings tab, then generate a grounded report here.
        </div>
      ) : (
        <div className="space-y-2">
          {reports.map((r) => (
            <div
              key={r.report_id}
              onClick={() => handleSelectReport(r)}
              className="p-3 bg-card/40 border border-border/40 rounded text-xs cursor-pointer hover:border-primary/50 hover:bg-card/60 transition-all flex items-start justify-between gap-3 group"
            >
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 flex-wrap">
                  <ScrollText className="w-3.5 h-3.5 text-primary flex-shrink-0" />
                  <span className="font-bold text-foreground truncate">{r.title}</span>
                  <span
                    className={`px-1.5 py-0.5 rounded border text-[10px] font-bold uppercase ${STATUS_COLORS[r.status] || "text-muted-foreground"}`}
                  >
                    {r.status}
                  </span>
                </div>
                <div className="text-[10px] text-muted-foreground mt-1 flex gap-3 flex-wrap">
                  <span className="flex items-center gap-1">
                    <Hash className="w-2.5 h-2.5" />{r.report_id}
                  </span>
                  {r.model_used && (
                    <span className="flex items-center gap-1">
                      <Cpu className="w-2.5 h-2.5" />{r.model_used}
                    </span>
                  )}
                  {r.created_by_email && (
                    <span className="flex items-center gap-1">
                      <User className="w-2.5 h-2.5" />{r.created_by_email}
                    </span>
                  )}
                  {r.created_at && (
                    <span className="flex items-center gap-1">
                      <Calendar className="w-2.5 h-2.5" />
                      {new Date(r.created_at).toLocaleString("en-IN")}
                    </span>
                  )}
                </div>
              </div>
              <Eye className="w-4 h-4 text-muted-foreground opacity-60 group-hover:opacity-100 flex-shrink-0 mt-0.5" />
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
