"""
Canonical Schema Extensions Registry.
Auto-generated by backend/pipelines/ingest_ai_router.py
"""

DYNAMIC_ENTITY_TYPES = {
    "drone": "Auto-created EntityType from c:\\Users\\shrih\\Desktop\\lmaoded\\Chandigarh-Police-1st-MVP\\backend\\test_data_drone_telemetry.csv",
    "crypto wallet": "Auto-created EntityType from C:\\Users\\shrih\\Desktop\\lmaoded\\Chandigarh-Police-1st-MVP\\backend\\real_data_files\\elliptic\\wallets_classes.csv"
}

DYNAMIC_ACTIVITY_TYPES = {
    "telegram_message": "Telegram messaging transmission event",
    "network_flow": "TCP/IP Network packet flow telemetry event",
    "location_ping": "GPS spatial location ping event",
    "darknet_scrape": "Marketplace listing web scrape event"
}

AUTO_CREATED_CATEGORIES_LOG = [
    {
        "category_name": "crypto wallet",
        "category_type": "EntityType",
        "source_file": "C:\\Users\\shrih\\Desktop\\lmaoded\\Chandigarh-Police-1st-MVP\\backend\\real_data_files\\elliptic\\wallets_classes.csv",
        "timestamp": "2026-09-05T10:24:53.853631+00:00"
    }
]
