"""
Canonical Schema Extensions Registry.
Auto-generated by backend/pipelines/ingest_ai_router.py
"""

DYNAMIC_ENTITY_TYPES = {
    "drone": "Auto-created EntityType from c:\\Users\\shrih\\Desktop\\lmaoded\\Chandigarh-Police-1st-MVP\\backend\\test_data_drone_telemetry.csv",
    "crypto wallet": "Auto-created EntityType from C:\\Users\\shrih\\Desktop\\lmaoded\\Chandigarh-Police-1st-MVP\\backend\\real_data_files\\elliptic\\wallets_classes.csv",
    "observed": "Auto-created EntityType from E:\\Manomoy\\PEC\\Hackathons\\Chandigarh Police\\1st round mvp\\backend\\real_data\\cache\\network_real.json",
    "inferred": "Auto-created EntityType from E:\\Manomoy\\PEC\\Hackathons\\Chandigarh Police\\1st round mvp\\backend\\real_data\\cache\\network_real.json"
}

DYNAMIC_ACTIVITY_TYPES = {
    "telegram_message": "Telegram messaging transmission event",
    "network_flow": "TCP/IP Network packet flow telemetry event",
    "location_ping": "GPS spatial location ping event",
    "darknet_scrape": "Marketplace listing web scrape event"
}

AUTO_CREATED_CATEGORIES_LOG = [
    {
        "category_name": "observed",
        "category_type": "EntityType",
        "source_file": "E:\\Manomoy\\PEC\\Hackathons\\Chandigarh Police\\1st round mvp\\backend\\real_data\\cache\\network_real.json",
        "timestamp": "2026-09-05T17:54:24.126028+00:00"
    },
    {
        "category_name": "inferred",
        "category_type": "EntityType",
        "source_file": "E:\\Manomoy\\PEC\\Hackathons\\Chandigarh Police\\1st round mvp\\backend\\real_data\\cache\\network_real.json",
        "timestamp": "2026-09-05T17:54:24.153930+00:00"
    }
]
