from datetime import datetime, timezone
import logging
import uuid
from typing import Optional

from sqlalchemy.orm import Session

from crawler.models.source import Source
from crawler.models.crawler_run import CrawlerRun
from crawler.models.raw_record import RawRecord
from crawler.collectors.registry import CollectorRegistry
from crawler.collectors.transport import DirectHTTPTransport, TorProxyTransport
from crawler.policy.robots_checker import RobotsChecker
from crawler.policy.rate_limiter import RateLimiter
from crawler.keywords.service import KeywordService
from crawler.pipeline.cleaner import ContentCleaner
from crawler.pipeline.dedup import Deduplicator
from crawler.pipeline.language import LanguageDetector
from crawler.pipeline.relevance_filter import KeywordMatcher
from crawler.pipeline.relevance_classifier import LLMRelevanceClassifier
from crawler.pipeline.entity_extractor import EntityExtractor
from crawler.evidence.tagging import EvidenceTagger

logger = logging.getLogger(__name__)


async def run_crawl(
    source_id: str,
    case_id: Optional[str] = None,
    triggered_by: Optional[int] = None,
    db: Optional[Session] = None,
) -> CrawlerRun:
    """
    Executes an end-to-end crawler pipeline flow parameterized by
    (source_id, case_id).

    Coordinates collectors, policies, deduplication, filtering,
    AI classification, entity extraction, and evidence provenance
    tagging.
    """

    if db is None:
        from database import SessionLocal

        db = SessionLocal()
        should_close_db = True
    else:
        should_close_db = False

    # 1. Create CrawlerRun record
    run = CrawlerRun(
        id=uuid.uuid4(),
        source_id=(
            uuid.UUID(str(source_id))
            if isinstance(source_id, str)
            else source_id
        ),
        case_id=case_id,
        status="RUNNING",
        started_at=datetime.now(timezone.utc),
        triggered_by=triggered_by,
    )

    db.add(run)
    db.commit()

    try:
        # 2. Resolve source and active keywords
        source = (
            db.query(Source)
            .filter(Source.id == run.source_id)
            .first()
        )

        if not source:
            run.status = "FAILED"
            run.error_summary = (
                f"Source with ID {source_id} not found."
            )
            run.finished_at = datetime.now(timezone.utc)
            db.commit()
            return run

        active_keywords = KeywordService.get_active_keywords(
            db,
            case_id=case_id,
        )

        source_config = dict(source.config or {})
        source_config["keywords"] = active_keywords

        # 3. Instantiate collector & transport
        collector = CollectorRegistry.get_collector(
            source.source_type
        )

        if source.transport_type == "tor_proxy":
            transport = TorProxyTransport()
        else:
            transport = DirectHTTPTransport()

        # 4. Fetch raw records from collector
        fetched_records = await collector.fetch(
            source_config,
            transport,
        )

        # Persist recursive discovery state generated by the collector.
        #
        # This is important because GoogleDiscoveryCollector stores its
        # query queue / seen state inside source_config["_discovery_state"].
        source.config = source_config

        run.urls_attempted = len(fetched_records)

        # Make the initial run state visible immediately.
        db.commit()

        robots_checker = RobotsChecker()

        rate_limiter = RateLimiter(
            default_delay=float(
                source.crawl_delay_seconds or 1.0
            )
        )

        classifier = LLMRelevanceClassifier()
        extractor = EntityExtractor()

        # 5. Process each record through pipeline
        for rec in fetched_records:
            # Refresh state so the crawler can notice a Stop request
            # made by another API request.
            db.refresh(source)
            db.refresh(run)

            if run.status == "STOPPED" or not source.is_active:
                run.status = "STOPPED"
                run.finished_at = datetime.now(timezone.utc)
                run.error_summary = "Crawl stopped by operator."
                db.commit()
                return run

            url = rec.get("url")

            if not url:
                continue

            # Policy: robots.txt check
            allowed = await robots_checker.is_allowed(
                url=url,
                user_agent="DarkKnightCrawler/1.0",
                db=db,
                transport=transport,
            )

            if not allowed:
                run.urls_skipped_robots += 1
                db.commit()
                continue

            # Policy: rate limiting
            await rate_limiter.wait_if_needed(
                url,
                requested_delay=float(
                    source.crawl_delay_seconds or 1.0
                ),
            )

            # Evidence Tagging & Provenance Validation
            try:
                rec_tagged = EvidenceTagger.tag_and_validate(
                    rec,
                    run_id=run.id,
                )
            except ValueError as ve:
                logger.error(
                    f"Provenance validation error for {url}: {ve}"
                )
                run.errors_count += 1
                db.commit()
                continue

            content_hash = rec_tagged["content_hash"]

            # Deduplication
            if Deduplicator.is_duplicate(
                content_hash,
                db,
            ):
                logger.info(
                    f"Duplicate content hash {content_hash} "
                    f"for {url}, skipping."
                )
                continue

            # Pipeline processing
            raw_text = rec_tagged.get("raw_text", "")

            cleaned_text = ContentCleaner.clean(
                raw_text
            )

            lang = LanguageDetector.detect(
                cleaned_text
            )

            # Keyword Pre-filter (cheap pass)
            matched_kws, is_passed = KeywordMatcher.match(
                cleaned_text,
                active_keywords,
            )

            if not is_passed:
                # Save discarded record without calling LLM
                raw_rec = RawRecord(
                    run_id=run.id,
                    source_id=source.id,
                    case_id=case_id,
                    url=url,
                    fetched_at=rec_tagged["fetched_at"],
                    raw_text=raw_text,
                    cleaned_text=cleaned_text,
                    content_hash=content_hash,
                    language=lang,
                    matched_keywords=[],
                    relevance_label="unrelated",
                    relevance_confidence=1.0,
                    relevance_reasoning=(
                        "No active keywords matched."
                    ),
                    extracted_candidates=[],
                    status="discarded",
                )

                db.add(raw_rec)

                run.records_produced += 1

                db.commit()
                continue

            # AI Relevance Classification
            rel_result = await classifier.classify(
                cleaned_text,
                matched_kws,
            )

            # Determine routing status
            if rel_result.label == "relevant":
                status_val = "pending_mapping"

                run.records_relevant += 1

                candidates = extractor.extract(
                    cleaned_text
                )

            elif (
                rel_result.confidence < 0.8
                or rel_result.label == "medical_legitimate"
            ):
                status_val = "review_queue"
                candidates = []

            else:
                status_val = "discarded"
                candidates = []

            # Save RawRecord output contract row
            raw_rec = RawRecord(
                run_id=run.id,
                source_id=source.id,
                case_id=case_id,
                url=url,
                fetched_at=rec_tagged["fetched_at"],
                raw_text=raw_text,
                cleaned_text=cleaned_text,
                content_hash=content_hash,
                language=lang,
                matched_keywords=matched_kws,
                relevance_label=rel_result.label,
                relevance_confidence=rel_result.confidence,
                relevance_reasoning=rel_result.reasoning,
                extracted_candidates=candidates,
                status=status_val,
            )

            db.add(raw_rec)

            run.records_produced += 1

            # Commit after each processed record so the frontend
            # can see activity while the crawl is still running.
            db.commit()

        # 6. Crawl completed
        run.status = "COMPLETED"
        run.finished_at = datetime.now(timezone.utc)

        db.commit()

    except Exception as exc:
        db.rollback()

        run.status = "FAILED"
        run.error_summary = str(exc)
        run.finished_at = datetime.now(timezone.utc)

        db.commit()

        logger.error(
            f"Crawler run failed: {exc}",
            exc_info=True,
        )

    finally:
        if should_close_db:
            db.close()

    return run